name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_PRIVATE_KEY }}

      - name: Copy files to EC2
        run: scp -r ./* ${{ secrets.EC2_USERNAME }}@54.72.186.52:/home/${{ secrets.EC2_USERNAME }}/

      - name: SSH into EC2 and run index.html
        uses: appleboy/ssh-action@master
        with:
          host: 54.72.186.52
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            cd /home/${{ secrets.EC2_USERNAME }}
            python3 -m http.server 8000 &>/dev/null &
            echo "index.html running at http://$(curl -s ifconfig.me):8000"
