name: ResetEC2

# Trigger deployment only on push to main branch
on:
  push:
    branches:
      - main

jobs:
  reset:
    name: Reset EC2 to Initial Stage on main branch push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Remove Index.html file
        uses: appleboy/ssh-action@master
        with:
          host: 54.72.186.52
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            # Remove Index.html from web server directory
            sudo rm /var/www/html/index.html

      - name: Remove Apache
        uses: appleboy/ssh-action@master
        with:
          host: 54.72.186.52
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            # Stop Apache service
            sudo systemctl stop httpd

            # Disable Apache service to prevent it from starting on boot
            sudo systemctl disable httpd

            # Uninstall Apache
            sudo yum remove -y httpd

      - name: Remove additional files and directories
        uses: appleboy/ssh-action@master
        with:
          host: 54.72.186.52
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            # Remove all files and directories except /home and /home/ec2-user
            sudo find / -mindepth 1 -maxdepth 1 -not \( -name "home" -o -name "ec2-user" \) -exec rm -rf {} +

      - name: Reset completed
        run: echo "EC2 instance has been reset to its initial stage."
