name: Saveit

# Trigger deployment only on push to main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2 on main branch push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
          REMOTE_HOST: 54.72.186.52
          REMOTE_USER: ${{ secrets.EC2_USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}

      - name: Execute remote commands
        uses: appleboy/ssh-action@master
        with:
          host: 54.72.186.52
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            sudo yum update -y
            if ! rpm -q httpd; then
              sudo yum install -y httpd
            fi
            sudo systemctl start httpd
            sudo systemctl enable httpd
            cd home
            sudo mv * /var/www/html
            sudo systemctl restart httpd
