name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  Upload-To-EC2:
    runs-on: ubuntu-latest

    steps:
      # - name: Checkout code
      #   uses: actions/checkout@v2

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: 54.72.186.52
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            # Stop existing Node.js server
            PID=$(sudo lsof -t -i:5500)
            if [ ! -z "$PID" ]; then
              sudo kill -9 $PID
            fi
            
            # Remove previous repository
            rm -rf SaveIt-Frontend

            # Clone new repository
            git clone https://github.com/chandni-khan/SaveIt-Frontend.git
            
            # Start Node.js server
            sudo nohup node server.js > output.log 2>&1 &
